name: Build Release artifacts

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build_release_artifacts:
    name: Download and Build artifacts
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v3
      id: download_artifacts
      with:
        path: ${{ runner.temp }}\grpc-labview-artifacts

    - name: Stage Artifacts
      run:
       python ${{runner.workspace}}\grpc-labview\build-it\stage_artifacts.py --downloaded_path ${{ steps.download_artifacts.outputs.download-path }} --staging_path ${{ runner.temp }}\grpc-labview-staged-artifacts
    
    - name: Build VI Packages
      run:
       python ${{runner.workspace}}\grpc-labview\build-it\build.py --target All --pathToBinaries ${{ runner.temp }}\grpc-labview-staged-artifacts\TopLevelDlls

    - name: Zip Release Artifacts
      run: |
        cd ${{runner.workspace}}/grpc-labview/labview source/Builds
        tar -cavf grpc-labview.zip *.vip

    - if: startsWith(github.ref, 'refs/tags/v')
      name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        name: Verison ${{ github.ref }}
        draft: true

    - if: startsWith(github.ref, 'refs/tags/v')
      name: Upload Release Artifacts to Draft Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{runner.workspace}}/grpc-labview/labview source/Builds/grpc-labview.zip
          asset_name: grpc-labview.zip
          asset_content_type: application/zip
